import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { load } from 'js-yaml';
import { Registry } from 'apcore-js';
import { createScannedModule } from 'apcore-toolkit';
import {
  modulesToBindings,
  renderBindingsYaml,
  writeBindingsFile,
} from '../../src/output/yaml-writer.js';
import { toModuleAnnotations } from '../../src/utils/module-factory.js';
import { ApBindingLoader } from '../../src/bridge/binding-loader.js';
import { ApcoreRegistry } from '../../src/core/registry.js';

const modules = () => [
  createScannedModule({
    moduleId: 'todos.list',
    description: 'GET /todos',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    tags: ['http'],
    target: 'GET /todos',
    annotations: toModuleAnnotations({ readonly: true }),
    documentation: 'Lists todos.',
  }),
  createScannedModule({
    moduleId: 'todos.create',
    description: 'POST /todos',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    tags: [],
    target: 'POST /todos',
  }),
];

describe('modulesToBindings', () => {
  it('emits snake_case keys', () => {
    const [first] = modulesToBindings(modules());
    expect(first).toMatchObject({
      module_id: 'todos.list',
      target: 'GET /todos',
      description: 'GET /todos',
      tags: ['http'],
      documentation: 'Lists todos.',
    });
    expect(first.annotations).toMatchObject({ readonly: true });
  });

  it('omits empty tags, annotations, and documentation', () => {
    const [, second] = modulesToBindings(modules());
    expect(second.tags).toBeUndefined();
    expect(second.annotations).toBeUndefined();
    expect(second.documentation).toBeUndefined();
  });
});

describe('renderBindingsYaml', () => {
  it('produces a commented, parseable document', () => {
    const text = renderBindingsYaml(modules());
    expect(text.startsWith('# Generated by hono-apcore')).toBe(true);
    expect((load(text) as { bindings: unknown[] }).bindings).toHaveLength(2);
  });
});

describe('writeBindingsFile', () => {
  it('writes a file the binding loader can read back', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'hono-apcore-out-'));
    const file = join(dir, 'nested', 'bindings.yaml');

    await expect(writeBindingsFile(modules(), file)).resolves.toBe(file);
    expect(await readFile(file, 'utf-8')).toContain('todos.list');

    const registry = new ApcoreRegistry(new Registry());
    await expect(new ApBindingLoader(registry).loadFromFile(file)).resolves.toEqual([
      'todos.list',
      'todos.create',
    ]);
  });
});
