import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { load } from 'js-yaml';
import { main } from '../../src/cli.js';

const APP = './tests/fixtures/demo-app.mjs';
const APCORE_APP = './tests/fixtures/demo-apcore.mjs';

let stdout: string[];
let stderr: string[];

beforeEach(() => {
  stdout = [];
  stderr = [];
  vi.spyOn(process.stdout, 'write').mockImplementation((chunk) => {
    stdout.push(String(chunk));
    return true;
  });
  vi.spyOn(process.stderr, 'write').mockImplementation((chunk) => {
    stderr.push(String(chunk));
    return true;
  });
});

afterEach(() => {
  vi.restoreAllMocks();
});

describe('hono-apcore CLI', () => {
  it('prints usage with no arguments and with --help', async () => {
    await expect(main([])).resolves.toBe(0);
    expect(stdout.join('')).toContain('hono-apcore <command> <entry>');

    stdout.length = 0;
    await expect(main(['--help'])).resolves.toBe(0);
    expect(stdout.join('')).toContain('Commands:');
  });

  it('prints the version', async () => {
    await expect(main(['--version'])).resolves.toBe(0);
    expect(stdout.join('')).toMatch(/hono-apcore \(apcore-js \d+\.\d+\.\d+\)/);
  });

  it('rejects an unknown command', async () => {
    await expect(main(['frobnicate', APP])).resolves.toBe(2);
    expect(stderr.join('')).toContain('unknown command "frobnicate"');
  });

  it('requires an entry module', async () => {
    await expect(main(['scan'])).resolves.toBe(2);
    expect(stderr.join('')).toContain('needs an entry module');
  });

  it('scans a plain Hono app into a table', async () => {
    await expect(main(['scan', APP])).resolves.toBe(0);
    const output = stdout.join('');
    expect(output).toContain('todos.list');
    expect(output).toContain('todos.create');
  });

  it('scans to JSON', async () => {
    await expect(main(['scan', APP, '--format', 'json'])).resolves.toBe(0);
    const modules = JSON.parse(stdout.join('')) as Array<{ module_id: string }>;
    expect(modules.map((m) => m.module_id)).toContain('todos.get');
  });

  it('scans to markdown', async () => {
    await expect(main(['scan', APP, '--format', 'markdown'])).resolves.toBe(0);
    expect(stdout.join('')).toContain('todos.list');
  });

  it('scans to a bindings YAML file', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'hono-apcore-cli-'));
    const file = join(dir, 'bindings.yaml');

    await expect(main(['scan', APP, '--format', 'yaml', '--out', file])).resolves.toBe(0);

    const parsed = load(await readFile(file, 'utf-8')) as { bindings: { module_id: string }[] };
    expect(parsed.bindings.map((b) => b.module_id)).toEqual([
      'todos.list',
      'todos.get',
      'todos.create',
    ]);
  });

  it('prints bindings YAML to stdout without --out', async () => {
    await expect(main(['scan', APP, '--format', 'yaml'])).resolves.toBe(0);
    expect(stdout.join('')).toContain('# Generated by hono-apcore');
  });

  it('applies --prefix, --include, and --exclude', async () => {
    await expect(
      main(['scan', APP, '--format', 'json', '--prefix', 'svc', '--exclude', 'create']),
    ).resolves.toBe(0);

    const ids = (JSON.parse(stdout.join('')) as Array<{ module_id: string }>).map(
      (m) => m.module_id,
    );
    expect(ids).toEqual(['svc.todos.list', 'svc.todos.get']);
  });

  it('writes JSON scan output to a file', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'hono-apcore-cli-'));
    const file = join(dir, 'modules.json');

    await expect(main(['scan', APP, '--format', 'json', '--out', file])).resolves.toBe(0);
    expect(stdout.join('')).toContain(`Wrote ${file}`);
    expect(JSON.parse(await readFile(file, 'utf-8'))).toHaveLength(3);
  });

  it('resolves a named export', async () => {
    await expect(main(['scan', `${APCORE_APP}:app`, '--format', 'json'])).resolves.toBe(0);
    expect(stdout.join('')).toContain('ping.list');
  });

  it("honours the entry's own route options, whatever the instance is named", async () => {
    await expect(main(['scan', `${APCORE_APP}:app`, '--format', 'json'])).resolves.toBe(0);

    const ids = (JSON.parse(stdout.join('')) as Array<{ module_id: string }>).map(
      (m) => m.module_id,
    );
    expect(ids).toEqual(['ping.list']);
  });

  it('lets a CLI flag override the entry configuration', async () => {
    await expect(
      main(['scan', `${APCORE_APP}:app`, '--format', 'json', '--prefix', 'svc']),
    ).resolves.toBe(0);
    expect(stdout.join('')).toContain('svc.ping.list');
  });

  it('reports a missing named export', async () => {
    await expect(main(['scan', `${APP}:nope`])).rejects.toThrow(/no export named "nope"/);
  });

  it('refuses to scan an entry with no Hono app', async () => {
    await expect(main(['scan', './tests/fixtures/no-app.mjs'])).rejects.toThrow(
      /does not export a Hono app/,
    );
  });

  it('exports OpenAI tool definitions, discovering the apcore instance', async () => {
    await expect(main(['export', APCORE_APP])).resolves.toBe(0);
    const tools = JSON.parse(stdout.join('')) as Array<{ function: { name: string } }>;
    expect(tools.map((t) => t.function.name)).toEqual(
      expect.arrayContaining(['demo-echo', 'ping-list']),
    );
  });

  it('exports from a plain app with no apcore surface', async () => {
    await expect(main(['export', APP])).resolves.toBe(0);
    expect(JSON.parse(stdout.join('')).length).toBeGreaterThan(0);
  });
});
