import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import * as yaml from 'js-yaml';
import { annotationsToDict } from 'apcore-toolkit';
import type { ScannedModule } from 'apcore-toolkit';

/** One entry of the `bindings:` list in a bindings YAML file. */
export interface BindingRecord {
  module_id: string;
  target: string;
  description: string;
  input_schema?: Record<string, unknown>;
  output_schema?: Record<string, unknown>;
  tags?: string[];
  annotations?: Record<string, unknown>;
  documentation?: string;
}

/**
 * Serialise scanned modules into the `bindings:` shape that
 * {@link ApBindingLoader} reads back.
 *
 * Keys are snake_case, matching the wire format shared by every apcore SDK.
 */
export function modulesToBindings(modules: ScannedModule[]): BindingRecord[] {
  return modules.map((module) => {
    const record: BindingRecord = {
      module_id: module.moduleId,
      target: module.target,
      description: module.description,
      input_schema: { ...module.inputSchema },
      output_schema: { ...module.outputSchema },
    };

    if (module.tags.length > 0) record.tags = [...module.tags];
    if (module.annotations) {
      record.annotations = annotationsToDict(module.annotations) as Record<string, unknown>;
    }
    if (module.documentation) record.documentation = module.documentation;

    return record;
  });
}

/** Render scanned modules as the text of a bindings YAML file. */
export function renderBindingsYaml(modules: ScannedModule[]): string {
  const header =
    '# Generated by hono-apcore. Load with HonoApcore.loadBindings() or\n' +
    '# `hono-apcore serve --bindings <file>`.\n';
  return header + yaml.dump({ bindings: modulesToBindings(modules) }, { noRefs: true, lineWidth: 100 });
}

/**
 * Write scanned modules to a single bindings YAML file, creating parent
 * directories as needed.
 *
 * @param modules  - Modules to serialise.
 * @param filePath - Destination path, e.g. `./bindings.yaml`.
 * @returns The path that was written.
 */
export async function writeBindingsFile(
  modules: ScannedModule[],
  filePath: string,
): Promise<string> {
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, renderBindingsYaml(modules), 'utf-8');
  return filePath;
}
